# Generated by Django 6.0.6 on 2026-09-09 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('Royal Crown Director', 'Royal Crown Director'), ('Crown Director', 'Crown Director'), ('Director', 'Director'), ('Senior Manager', 'Senior Manager'), ('Manager', 'Manager'), ('Executive', 'Executive'), ('Senior Leader', 'Senior Leader'), ('Leader', 'Leader'), ('Builder', 'Builder'), ('Associate', 'Associate')], default='Associate', max_length=50)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('pbv', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cgv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_percentage', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downline_members', to='distributors.distributor')),
            ],
            options={
                'db_table': 'distributors',
                'ordering': ['-cgv'],
            },
        ),
    ]
