# Generated by Django 6.0.6 on 2026-09-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='rank',
            field=models.CharField(choices=[('Associate', 'Associate'), ('Builder', 'Builder'), ('Leader', 'Leader'), ('Senior Leader', 'Senior Leader'), ('Executive', 'Executive'), ('Manager', 'Manager'), ('Senior Manager', 'Senior Manager'), ('Director', 'Director'), ('Crown Director', 'Crown Director'), ('Royal Crown Director', 'Royal Crown Director')], default='Associate', max_length=50),
        ),
    ]
