# Generated by Django 6.0.6 on 2026-09-09 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('performance_level', models.CharField(choices=[('Seed', 'Seed'), ('Bloom', 'Bloom'), ('Garden', 'Garden'), ('Emerald', 'Emerald'), ('Diamond', 'Diamond'), ('Crown', 'Crown'), ('Gold Crown', 'Gold Crown')], default='Seed', max_length=20)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus_percentage', models.DecimalField(decimal_places=2, default=3.5, max_digits=5)),
                ('customers', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('established_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='distributors.distributor')),
            ],
            options={
                'db_table': 'shops',
                'ordering': ['-monthly_revenue'],
            },
        ),
    ]
