# Generated by Django 6.0.6 on 2026-09-11 02:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_shop_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5),
        ),
    ]
