# Generated by Django 6.0.6 on 2026-09-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_bonus_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-owner_bv', '-monthly_revenue']},
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_bv',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total BV the owner has sold via their products.', max_digits=14),
        ),
    ]
