# Generated by Django 6.0.6 on 2026-09-11 02:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_shop_options_shop_owner_bv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='AUTO-COMPUTED from performance_level.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='shop',
            name='customers',
            field=models.PositiveIntegerField(default=0, help_text='AUTO-COMPUTED: distinct customers who shopped at this shop.'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner_bv',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='AUTO-COMPUTED: total BV the owner has sold.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='shop',
            name='performance_level',
            field=models.CharField(choices=[('Seed', 'Seed'), ('Bloom', 'Bloom'), ('Garden', 'Garden'), ('Emerald', 'Emerald'), ('Diamond', 'Diamond'), ('Crown', 'Crown'), ('Gold Crown', 'Gold Crown')], default='Seed', help_text='AUTO-COMPUTED from owner_bv.', max_length=20),
        ),
    ]
