# Generated by Django 6.0.6 on 2026-09-11 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('distributors', '0003_alter_distributor_rank'),
        ('shops', '0005_alter_shop_bonus_percentage_alter_shop_customers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='code',
            field=models.CharField(db_index=True, editable=False, help_text='Auto-generated unique cart code (e.g. OMA-A7B9-K2M4-P8QX).', max_length=24, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['shop', 'status'], name='carts_shop_id_528866_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['code'], name='carts_code_21c30d_idx'),
        ),
    ]
