# Generated by Django 6.0.6 on 2026-09-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('consistency', 'Consistency'), ('referral', 'Referral'), ('dynamic', 'Dynamic'), ('training', 'Training'), ('event', 'Event'), ('booking', 'Booking'), ('festival', 'Festival'), ('loyalty', 'Loyalty')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('month', models.CharField(max_length=15)),
                ('year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('processing', 'Processing')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bonuses',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
