# Generated by Django 6.0.6 on 2026-09-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0002_initial'),
        ('distributors', '0003_alter_distributor_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='type',
            field=models.CharField(choices=[('consistency', 'Consistency'), ('referral', 'Referral'), ('dynamic', 'Dynamic'), ('training', 'Training'), ('event', 'Event'), ('booking', 'Booking'), ('design', 'Design'), ('festival', 'Festival'), ('loyalty', 'Loyalty')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='bonus',
            constraint=models.UniqueConstraint(fields=('distributor', 'name', 'month', 'year'), name='unique_bonus_per_distributor_period'),
        ),
    ]
