# Generated by Django 6.0.6 on 2026-09-09 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0002_initial'),
        ('distributors', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='commission',
            name='source_distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_commissions', to='distributors.distributor'),
        ),
    ]
