# Generated by Django 6.0.6 on 2026-09-11 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_initial'),
        ('distributors', '0003_alter_distributor_rank'),
        ('orders', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='pbv',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The BV that this commission was calculated from.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='commission',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.UniqueConstraint(condition=models.Q(('source_distributor__isnull', False)), fields=('distributor', 'type', 'source_distributor'), name='unique_differential_per_source'),
        ),
    ]
