# Generated by Django 6.0.6 on 2026-09-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('legacy_circle', 'Legacy Circle'), ('legacy', 'Legacy'), ('annual', 'Annual'), ('special', 'Special')], max_length=20)),
                ('prize', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('past', 'Past'), ('upcoming', 'Upcoming')], default='active', max_length=20)),
                ('given_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'awards',
                'ordering': ['-year', '-given_date'],
            },
        ),
    ]
