# Generated by Django 6.0.6 on 2026-09-09 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awards', '0001_initial'),
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='distributors.distributor'),
        ),
    ]
