# Generated by Django 6.0.6 on 2026-09-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_initial'),
        ('distributors', '0003_alter_distributor_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['-year', 'name']},
        ),
        migrations.AlterField(
            model_name='award',
            name='given_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='prize',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='award',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past', 'Past'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.UniqueConstraint(fields=('distributor', 'name', 'year'), name='unique_award_per_distributor_per_year'),
        ),
    ]
