# Generated by Django 6.0.6 on 2026-09-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.TextField(blank=True, help_text='Base64 encoded image (data:image/...;base64,...)', null=True),
        ),
    ]
