# Generated by Django 6.0.6 on 2026-09-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['type', 'class_type'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='class_type',
            field=models.CharField(choices=[('A', 'A — Table / Home / Office / Church flowers'), ('B', 'B — Wedding / Graduation flowers'), ('C', 'C — Gift & Premium flower packages'), ('D', 'D — Decoration kits & Event decoration')], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='bv',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to inherit from the category.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to inherit from the category.', max_digits=12, null=True),
        ),
    ]
