# Generated by Django 6.0.6 on 2026-09-10 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_initial'),
        ('products', '0003_alter_category_options_alter_category_class_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='The distributor who earns PBV/CGV when this product is sold.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_sold', to='distributors.distributor'),
        ),
    ]
